AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Learning AWS SAM
Resources:
  HelloLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloLambda
      Handler: index.lambda_handler
      Runtime: ruby2.5 
      CodeUri: src 
      MemorySize: 128 
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        MyEndpoint:
          Type: Api 
          Properties:
            Path: /test
            Method: get
      Environment:
        Variables:
          table_name: SampleTable
  SampleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: SampleTable
      PrimaryKey:
        Name: name
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1